name: Pull Projects

on:
  schedule:
    - cron: '*/15 * * * *'
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  pull_projects:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Repositories
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Pull submodules
        run: |
          git submodule update --remote --merge
          git config --global user.email "${{ github.actor }}@users.noreply.github.com"
          git config --global user.name "${{ github.actor }}"
          current_time=$(TZ='Etc/GMT-5' date +"%Y-%m-%d %H:%M:%S %Z")
          git add .
          if git diff --cached --exit-code > /dev/null; then
            echo "No changes to commit"
          else
            git commit -m "Обновление проектов до последних коммитов $current_time"
            git push
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
